app_order/urls.py
from django.urls import path
from app_order import views
app_name = "app_order"

urlpatterns = [
   path('add/<pk>/',views.add_to_cart, name="add"),
   path('cart/', views.Cart_View,name="cart"),
   path('remove/<pk>/',views.Remove_from_cart,name="remove"),
   path('increase/<pk>/', views.increase_item,name="increase"),
   path('decrease/<pk>/',views.decrease_item,name="decrease")


]

app_shop/urls.py
from django.urls import path
from app_shop import views

app_name = 'app_shop'

urlpatterns = [
     path('',views.Home.as_view(),name="Home"),
     path('product/<pk>/',views.ProductDetail.as_view(),name="product-detail"),

]

my_ecom_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_shop.urls')),
    path('account/',include('app_login.urls')),
    path('shop/',include('app_order.urls')),
    path('payment/',include('app_payment.urls')),
    

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app_shop/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Categories"
class Product(models.Model):
    mainimage = models.ImageField(upload_to=True)
    name = models.CharField(max_length=250)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name="category")
    preview_text = models.TextField(max_length=250,verbose_name="Preview Text")
    Detail_text = models.TextField(max_length=1000,verbose_name="Description")
    price= models.FloatField()
    old_Price = models.FloatField(default=0.00)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    class Meta:
        ordering= ["-created",]

app_shop/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView,DetailView
from app_shop.models import Product
from django.contrib.auth.mixins import LoginRequiredMixin

class Home(ListView):
    model = Product
    template_name = "app_shop/Home.html"
class ProductDetail(LoginRequiredMixin,DetailView):
    model = Product
    template_name = "app_shop/product_detail.html"

templates/app_shop/Home.html
{% extends 'base.html'%}
{% block body_block %}
<div class="container my-5">
  <h1 class=-"my-5">Features Product</h1>

  <div class="row">
    {% for product in object_list %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px" alt="">
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"><a href="{% url 'app_shop:product-detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="new-price">&#2547;{{product.price|floatformat:2}}</span>
              <span class="old-Price"><strike>&#2547;{{product.old_Price|floatformat:2}}</strike></span>
            </div>

          </div>

        </figcaption>
      </figure>


    </div>
{% endfor %}
  </div>

</div>



{% endblock %}

templates/app_shop/product_detail.html
{% extends 'base.html'%}
{% block body_block %}
<div class="container my-5">
  <div class="card">
    <div class="row">
      <aside class="col-sm-5 border-right">
        <article class="gallery-wrap">
          <div class="img-big-wrap">
            <div>
              <a href="#"><img src="/media/{{object.mainimage}}" alt="" style="width:450px"></a>

            </div>

          </div>

        </article>

      </aside>
      <aside class="col-sm-7">
        <article class="card-body p-5">
          <h3 class="title mp-3">{{object.name}}</h3>
          <p class="price-detail-wrap">
            <span class="price h3 text-warning">
            <span class="currency">BDT &#2547;</span><span class="num">{{object.price}}</span>

          </span></p>

          <dl class="item-property">
            <dt>Description</dt>
            <dd><p>
              {{object.Detail_text|linebreaks}}

            </p></dd>

          </dl>
          <a href="{% url 'app_order:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"><i class="fa fa-shopping-cart"> Add TO Cart</i></a>

        </article>

      </aside>

    </div>

  </div>

</div>

{% endblock %}