app_login/urls.py
from django.urls import path
from app_login import views

app_name = 'app_login'

urlpatterns = [
    path('Signup/',views.Signup,name='signup'),
    path('login/',views.login_user,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('profile/',views.profile_user,name='profile')


]

app_order/urls.py
from django.urls import path
from app_order import views
app_name = "app_order"

urlpatterns = [
   path('add/<pk>/',views.add_to_cart, name="add"),
   path('cart/', views.Cart_View,name="cart"),
   path('remove/<pk>/',views.Remove_from_cart,name="remove"),
   path('increase/<pk>/', views.increase_item,name="increase"),
   path('decrease/<pk>/',views.decrease_item,name="decrease")


]

app_shop/urls.py
from django.urls import path
from app_shop import views

app_name = 'app_shop'

urlpatterns = [
     path('',views.Home.as_view(),name="Home"),
     path('product/<pk>/',views.ProductDetail.as_view(),name="product-detail"),

]

my_ecom_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_shop.urls')),
    path('account/',include('app_login.urls')),
    path('shop/',include('app_order.urls')),
    path('payment/',include('app_payment.urls')),
    

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
   <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>{%block title_block %} E.COM|BOHUBRIHI{% endblock %}</title>
    <style>
    .card{
      height: 350px;
    }
    .card-product::after{
      content:"";
      display:table;
      clear:both;
      visibility: hidden;
    }
    .card-product .price-new, .card-product .price{
      margin-right: 5px;
    }
    .card-product .old-price{
      color:#999;

    }
    .card-product .img-wrap {
      border-radious:3px 3px 0 0;
      overflow: hidden;
      position: relative;
      height: 220px;
      text-align: center;
    }
    .card-product .img-wrap img{
      max-width: 100%;
      max-height: 100%
      object-fit:cover;

    }

    .card-product .info-wrap{
      overflow: hidden;
      padding: 15px;
      border-top: 1px solid #eee;
    }

    .card-product .action-wrap{
      padding-top: 4px;
      margin-top: 4px;
    }
    .card-product .bottom-top{
      padding: 15px;
      border-top: 1px solid #eee;
    }

    .card-product .title{
      margin-top: 0px;
    }


    </style>
  </head>
  <body>
    {% include 'navber.html' %}
    <div class="container" >

      <div class="messages container mt-2">
        {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{message.tags}} {% endif %}" role="alert">
          {{message}}

        <button type="button" class="close" data-dismiss="alert" aria-label="close" <span aria-hidden="true">&times;</span></button>
        </div>
        {% endfor %}
        {% endif %}

      </div>
      {% block body_block%} {% endblock %}

    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/navber.html
{% load cart_tag %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="container">


  <a class="navbar-brand" href="#">Django E-commerce Project </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'app_order:cart'%}"><i class="fa fa-shopping-cart"> </i>Cart
          <span class="badge badge-light">{{request.user|cart_total}}</span></a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-user-tie"></i> {{request.user.profile.username}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'app_login:profile'%}">Profile</a>
              <a class="dropdown-item" href="#">Orders</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'app_login:logout'%}">Logout</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item active">
            <a class="btn btn-primary btn-sm" href="{% url 'app_login:login'%}">Login</a>
          </li>
          {% endif %}
        </ul>

  </div>
</div>
  </nav>