app_payment/urls.py
from django.urls import path
from app_payment import views
app_name = "app_payment"
urlpatterns = [
    path('checkout/',views.checkout,name='checkout'),
    path('payment/',views.payment,name="payment"),
]

app_shop/urls.py
from django.urls import path
from app_shop import views

app_name = 'app_shop'

urlpatterns = [
     path('',views.Home.as_view(),name="Home"),
     path('product/<pk>/',views.ProductDetail.as_view(),name="product-detail"),

]

my_ecom_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app_shop.urls')),
    path('account/',include('app_login.urls')),
    path('shop/',include('app_order.urls')),
    path('payment/',include('app_payment.urls')),
    

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

app_payment/models.py
from django.db import models

# Create your models here.
from django.conf import settings

class Billingaddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    address = models.CharField(max_length=265,blank=True)
    zipcode = models.CharField(max_length=10,blank=True)
    city = models.CharField(max_length=30,blank=True)
    country = models.CharField(max_length=20,blank=True)
    def __str__(self):
        return f'{self.user.profile.username}billing address'
    def is_fully_filled(self):
        field_names = [f.name for f in self._meta.get_fields()]
        for field_name in field_names:
            value = getattr(self,field_name)
            if value is None or value=='':
               return False
        return True
    class Meta:
         verbose_name_plural = "Billing Addresses"

app_payment/forms.py
from django import forms
from app_payment.models import Billingaddress
class BillingForm(forms.ModelForm):
    class Meta:
        model = Billingaddress
        fields = ['address','zipcode','city','country']
        

app_payment/views.py
from django.shortcuts import render
from app_order.models import Order
from app_payment.models import Billingaddress
from app_payment.forms import BillingForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
@login_required
def checkout(request):
    saved_address = Billingaddress.objects.get_or_create(user=request.user)
    saved_address = saved_address[0]
    form = BillingForm(instance=saved_address)
    if request.method == 'POST':
        form = BillingForm(request.POST,instance=saved_address)
        if form.is_valid():
            form.save()
            form = BillingForm(instance=saved_address)
            messages.success(request,f"Shipping Address Saved!")
    order_qs = Order.objects.filter(user=request.user,ordered=False)

    order_items = order_qs[0].orderitem.all()
    order_total = order_qs[0].get_totals()
    return render(request,'app_payment/checkout.html',context={'form':form, 'order_items':order_items,"order_total":order_total,'saved_address':saved_address})

templates/app_payment/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
<div class="container mt-5">
  <h2 class="mb-3">

Shopping Address> <span class="text-muted"> checkout</span>

  </h2>
 <div class="row">
   <div class="col-md-9">
     <div class="card mb-5" style="height:auto">
       <div class="card-body">
         <form method="POST">
           {{form|crispy}}
           {% csrf_token %}
           <button type="submit" class="btn btn-primary float-right"> Save Address</button>

         </form>

       </div>


     </div>

   </div>
   <div class="col-md-3">
     <div class="card" style="height:auto">
       <div class="card-body">
         <ul class="list-group list-group-flush">
        {% for order_item in order_items %}
           <li class="list-group-
           item">{{order_item.item.name}} x {{order_item.quantity}}</li>
        {% endfor %}

         </ul>

       </div>
       <div class="card-footer">
         <span class="float-left"><b>Order Total </b></span>
         <span class="float_right"><b>&#2547;{{order_total|floatformat:2}}</b></span>

       </div>

     </div>
   {% if saved_address.is_fully_filled %}
   <a href="{% url "app_payment:payment" %}"  class="btn btn-warning btn-md">Make Payment</a>
     {% else %}
     <div class="alert alert-info">
       <p>Please fill up all the information to make payment</p>

     </div>
     {% endif %}
   </div>

 </div>

</div>
{% endblock %}